// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasswordManager.EntityFramework;

namespace PasswordManager.EntityFramework.Migrations
{
    [DbContext(typeof(PasswordManagerDbContext))]
    [Migration("20211111062912_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PasswordManager.Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountHolderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountHolderId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PasswordManager.Domain.Models.PasswordGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordOfGroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("PasswordGroups");
                });

            modelBuilder.Entity("PasswordManager.Domain.Models.SavedAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CryptedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PasswordGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PasswordGroupId");

                    b.ToTable("SavedAccounts");
                });

            modelBuilder.Entity("PasswordManager.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PasswordManager.Domain.Models.Account", b =>
                {
                    b.HasOne("PasswordManager.Domain.Models.User", "AccountHolder")
                        .WithMany()
                        .HasForeignKey("AccountHolderId");

                    b.Navigation("AccountHolder");
                });

            modelBuilder.Entity("PasswordManager.Domain.Models.PasswordGroup", b =>
                {
                    b.HasOne("PasswordManager.Domain.Models.Account", null)
                        .WithMany("PasswordGroups")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("PasswordManager.Domain.Models.SavedAccount", b =>
                {
                    b.HasOne("PasswordManager.Domain.Models.PasswordGroup", null)
                        .WithMany("SavedAccounts")
                        .HasForeignKey("PasswordGroupId");
                });

            modelBuilder.Entity("PasswordManager.Domain.Models.Account", b =>
                {
                    b.Navigation("PasswordGroups");
                });

            modelBuilder.Entity("PasswordManager.Domain.Models.PasswordGroup", b =>
                {
                    b.Navigation("SavedAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
